import { GridColDef, GridLogicOperator } from '@mui/x-data-grid-pro';

export const columns: GridColDef<(typeof rows)[number]>[] = [
  { field: 'id', headerName: 'ID', width: 90 },
  { field: 'lastName', headerName: 'Last name', width: 150, editable: true },
  { field: 'firstName', headerName: 'First name', width: 150, editable: true },
  { field: 'age', headerName: 'Age', type: 'number', width: 110, editable: true },
  { field: 'house', headerName: 'House', width: 150, editable: false },
  { field: 'title', headerName: 'Title', width: 150, editable: false },
  { field: 'status', headerName: 'Status', width: 150, editable: false },
  { field: 'birthYear', headerName: 'Birth Year', type: 'number', width: 110, editable: false },
  { field: 'deathYear', headerName: 'Death Year', type: 'number', width: 110, editable: false },
  { field: 'allegiance', headerName: 'Allegiance', width: 150, editable: false },
  { field: 'weapon', headerName: 'Weapon', width: 150, editable: false },
  { field: 'nickname', headerName: 'Nickname', width: 150, editable: false },
  { field: 'actor', headerName: 'Actor', width: 150, editable: false },
  { field: 'episodes', headerName: 'Episodes', type: 'number', width: 110, editable: false },
  // not supported
  // {
  //   field: 'fullName',
  //   headerName: 'Full name',
  //   description: 'This column has a value getter and is not sortable.',
  //   sortable: false,
  //   width: 160,
  //   valueGetter: (_value, row) => `${row.firstName || ''} ${row.lastName || ''}`,
  // },
];

export const rows = [
  {
    id: 1,
    lastName: 'Snow',
    firstName: 'Jon',
    age: 35,
    house: 'Stark',
    title: 'King in the North',
    status: 'Alive',
    birthYear: 283,
    deathYear: null,
    allegiance: "Night's Watch",
    weapon: 'Longclaw',
    nickname: 'Lord Snow',
    actor: 'Kit Harington',
    episodes: 62,
  },
  {
    id: 2,
    lastName: 'Lannister',
    firstName: 'Cersei',
    age: 42,
    house: 'Lannister',
    title: 'Queen of the Andals',
    status: 'Deceased',
    birthYear: 266,
    deathYear: 305,
    allegiance: 'House Lannister',
    weapon: 'None',
    nickname: 'None',
    actor: 'Lena Headey',
    episodes: 62,
  },
  {
    id: 3,
    lastName: 'Stark',
    firstName: 'Arya',
    age: 18,
    house: 'Stark',
    title: 'Lady of Winterfell',
    status: 'Alive',
    birthYear: 289,
    deathYear: null,
    allegiance: 'House Stark',
    weapon: 'Needle',
    nickname: 'No One',
    actor: 'Maisie Williams',
    episodes: 59,
  },
  {
    id: 4,
    lastName: 'Targaryen',
    firstName: 'Daenerys',
    age: 25,
    house: 'Targaryen',
    title: 'Queen of Meereen',
    status: 'Deceased',
    birthYear: 284,
    deathYear: 305,
    allegiance: 'House Targaryen',
    weapon: 'Dragons',
    nickname: 'Dany',
    actor: 'Emilia Clarke',
    episodes: 62,
  },
  {
    id: 5,
    lastName: 'Lannister',
    firstName: 'Tyrion',
    age: 39,
    house: 'Lannister',
    title: 'Hand of the Queen',
    status: 'Alive',
    birthYear: 273,
    deathYear: null,
    allegiance: 'House Lannister',
    weapon: 'Crossbow',
    nickname: 'The Imp',
    actor: 'Peter Dinklage',
    episodes: 67,
  },
  {
    id: 6,
    lastName: 'Baratheon',
    firstName: 'Robert',
    age: 50,
    house: 'Baratheon',
    title: 'King of the Andals',
    status: 'Deceased',
    birthYear: 262,
    deathYear: 298,
    allegiance: 'House Baratheon',
    weapon: 'Warhammer',
    nickname: 'The Usurper',
    actor: 'Mark Addy',
    episodes: 7,
  },
  {
    id: 7,
    lastName: 'Greyjoy',
    firstName: 'Theon',
    age: 26,
    house: 'Greyjoy',
    title: 'Prince of Winterfell',
    status: 'Deceased',
    birthYear: 278,
    deathYear: 305,
    allegiance: 'House Greyjoy',
    weapon: 'Bow',
    nickname: 'Reek',
    actor: 'Alfie Allen',
    episodes: 47,
  },
  {
    id: 8,
    lastName: 'Mormont',
    firstName: 'Jorah',
    age: 44,
    house: 'Mormont',
    title: 'Lord of Bear Island',
    status: 'Deceased',
    birthYear: 257,
    deathYear: 305,
    allegiance: 'House Targaryen',
    weapon: 'Sword',
    nickname: 'None',
    actor: 'Iain Glen',
    episodes: 52,
  },
  {
    id: 9,
    lastName: 'Tyrell',
    firstName: 'Margaery',
    age: 23,
    house: 'Tyrell',
    title: 'Queen of the Seven Kingdoms',
    status: 'Deceased',
    birthYear: 283,
    deathYear: 303,
    allegiance: 'House Tyrell',
    weapon: 'None',
    nickname: 'None',
    actor: 'Natalie Dormer',
    episodes: 26,
  },
  {
    id: 10,
    lastName: 'Sand',
    firstName: 'Oberyn',
    age: 42,
    house: 'Martell',
    title: 'Prince of Dorne',
    status: 'Deceased',
    birthYear: 258,
    deathYear: 301,
    allegiance: 'House Martell',
    weapon: 'Spear',
    nickname: 'The Red Viper',
    actor: 'Pedro Pascal',
    episodes: 7,
  },
  {
    id: 11,
    lastName: 'Snow',
    firstName: 'Jon',
    age: 35,
    house: 'Stark',
    title: 'King in the North',
    status: 'Alive',
    birthYear: 283,
    deathYear: null,
    allegiance: "Night's Watch",
    weapon: 'Longclaw',
    nickname: 'Lord Snow',
    actor: 'Kit Harington',
    episodes: 62,
  },
  {
    id: 12,
    lastName: 'Stark',
    firstName: 'Eddard',
    age: 45,
    house: 'Stark',
    title: 'Warden of the North',
    status: 'Deceased',
    birthYear: 263,
    deathYear: 298,
    allegiance: 'House Stark',
    weapon: 'Ice',
    nickname: 'Ned',
    actor: 'Sean Bean',
    episodes: 9,
  },
  {
    id: 13,
    lastName: 'Stark',
    firstName: 'Catelyn',
    age: 40,
    house: 'Stark',
    title: 'Lady of Winterfell',
    status: 'Deceased',
    birthYear: 264,
    deathYear: 299,
    allegiance: 'House Stark',
    weapon: 'None',
    nickname: 'None',
    actor: 'Michelle Fairley',
    episodes: 25,
  },
  {
    id: 14,
    lastName: 'Stark',
    firstName: 'Robb',
    age: 20,
    house: 'Stark',
    title: 'King in the North',
    status: 'Deceased',
    birthYear: 283,
    deathYear: 299,
    allegiance: 'House Stark',
    weapon: 'Sword',
    nickname: 'The Young Wolf',
    actor: 'Richard Madden',
    episodes: 21,
  },
  {
    id: 15,
    lastName: 'Stark',
    firstName: 'Sansa',
    age: 18,
    house: 'Stark',
    title: 'Lady of Winterfell',
    status: 'Alive',
    birthYear: 286,
    deathYear: null,
    allegiance: 'House Stark',
    weapon: 'None',
    nickname: 'Little Bird',
    actor: 'Sophie Turner',
    episodes: 59,
  },
  {
    id: 16,
    lastName: 'Stark',
    firstName: 'Arya',
    age: 18,
    house: 'Stark',
    title: 'Lady of Winterfell',
    status: 'Alive',
    birthYear: 289,
    deathYear: null,
    allegiance: 'House Stark',
    weapon: 'Needle',
    nickname: 'No One',
    actor: 'Maisie Williams',
    episodes: 59,
  },
  {
    id: 17,
    lastName: 'Stark',
    firstName: 'Bran',
    age: 16,
    house: 'Stark',
    title: 'Three-Eyed Raven',
    status: 'Alive',
    birthYear: 290,
    deathYear: null,
    allegiance: 'House Stark',
    weapon: 'None',
    nickname: 'Bran the Broken',
    actor: 'Isaac Hempstead Wright',
    episodes: 40,
  },
  {
    id: 18,
    lastName: 'Stark',
    firstName: 'Rickon',
    age: 11,
    house: 'Stark',
    title: 'None',
    status: 'Deceased',
    birthYear: 295,
    deathYear: 303,
    allegiance: 'House Stark',
    weapon: 'None',
    nickname: 'None',
    actor: 'Art Parkinson',
    episodes: 16,
  },
  {
    id: 29,
    lastName: 'Lannister',
    firstName: 'Cersei',
    age: 42,
    house: 'Lannister',
    title: 'Queen of the Seven Kingdoms',
    status: 'Deceased',
    birthYear: 266,
    deathYear: 305,
    allegiance: 'House Lannister',
    weapon: 'None',
    nickname: 'None',
    actor: 'Lena Headey',
    episodes: 62,
  },
  {
    id: 30,
    lastName: 'Lannister',
    firstName: 'Jaime',
    age: 42,
    house: 'Lannister',
    title: 'Lord Commander of the Kingsguard',
    status: 'Deceased',
    birthYear: 266,
    deathYear: 305,
    allegiance: 'House Lannister',
    weapon: 'Sword',
    nickname: 'Kingslayer',
    actor: 'Nikolaj Coster-Waldau',
    episodes: 55,
  },
  {
    id: 31,
    lastName: 'Bolton',
    firstName: 'Ramsay',
    age: 24,
    house: 'Bolton',
    title: 'Lord of Winterfell',
    status: 'Deceased',
    birthYear: 275,
    deathYear: 303,
    allegiance: 'House Bolton',
    weapon: 'Bow',
    nickname: 'Bastard of Bolton',
    actor: 'Iwan Rheon',
    episodes: 20,
  },
  {
    id: 32,
    lastName: 'Baratheon',
    firstName: 'Joffrey',
    age: 19,
    house: 'Baratheon',
    title: 'King of the Seven Kingdoms',
    status: 'Deceased',
    birthYear: 286,
    deathYear: 303,
    allegiance: 'House Baratheon',
    weapon: 'Crossbow',
    nickname: 'None',
    actor: 'Jack Gleeson',
    episodes: 26,
  },
  {
    id: 33,
    lastName: 'Greyjoy',
    firstName: 'Euron',
    age: 40,
    house: 'Greyjoy',
    title: 'King of the Iron Islands',
    status: 'Deceased',
    birthYear: 265,
    deathYear: 305,
    allegiance: 'House Greyjoy',
    weapon: 'Axe',
    nickname: 'Crow’s Eye',
    actor: 'Pilou Asbæk',
    episodes: 15,
  },
];

export const gridDefaults = {
  filterModel: {
    items: [],
    logicOperator: 'and' as GridLogicOperator,
    quickFilterValues: [],
    quickFilterLogicOperator: 'and' as GridLogicOperator,
  },
  columnVisibilityModel: {},
  sortModel: [],
};
